Require matplotlib 1.3 or higher
This avoids the matplotlib bug in 1.1 (when using numpy >= 1.10),
which gives the error:
TypeError: histogram() got an unexpected keyword argument 'new'